<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEY6XxiB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEY6XxiB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEY6XxiB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEY6XxiB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEY6XxiB\App_KernelDevDebugContainer([
    'container.build_hash' => 'EY6XxiB',
    'container.build_id' => '2b4d889f',
    'container.build_time' => 1696323323,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEY6XxiB');
