<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJL1q1V6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJL1q1V6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJL1q1V6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJL1q1V6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJL1q1V6\App_KernelDevDebugContainer([
    'container.build_hash' => 'JL1q1V6',
    'container.build_id' => 'c2676a4e',
    'container.build_time' => 1696327294,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJL1q1V6');
